version: '3.3'
services:
  movie-mysql:
    image: sihyun2/mysql:v1
    ports:
      - 5556:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movie
    volumes:
      - /c/docker/movie_db/:/var/lib/mysql
    restart: always


  movie-springboot:
    depends_on:
      - movie-mysql
    image: sihyun2/movie-springboot:v1
    ports:
      - 8888:8080
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_SERVER=movie-mysql
      - MYSQL_PORT=3306
    volumes:
      - /c/upload/image/:/my-app/image/
    restart: always


  movie-react:
    depends_on:
      - movie-springboot
    build:
      context: https://github.com/Sihyun3/FrontEnd-Moive.git#main        
      args:          
        - REST_API_SERVER_IP=192.168.0.47
        - REST_API_SERVER_PORT=8888
    ports:
      - 80:80